### ISSUE TITLE
TTL is cached

### ISSUE THREAD

**Issue by codl** [jedisct1/encrypted-dns-server#33]
It seems the original TTL of records is cached and returned identical in each subsequent query response

Meaning, a record with a 24-hour TTL that was cached 23 hours ago and is queried now, looks to the client as if it will be fresh for the next 24 hours, even though it is only fresh for another hour.

Is this intentional? It's unlike every piece of DNS software I've used before, which update the ttl in each query so that downstream caches will expire at the same time as its own cache does

**Comment by jedisct1** [comment]
Client (at least `dnscrypt-proxy`) have their own cache (with decreasing TTLs).

Serving the real TTL is intentional in order to avoid a burst of queries every time a popular name is close to expiration.

When caching resolvers are chained, decreasing TTLs doesn't really make sense. It will only increase traffic utilization.

Not decreasing TTLs in intermediate caches is equivalent to having a local resolver without intermediates.

It would be different if `encrypted-dns-server` was the only cache in the chain.

**Comment by codl** [comment]
> Client (at least dnscrypt-proxy) have their own cache (with decreasing TTLs).

Right, but they start counting down when they talk to `encrypted-dns-server`, not when the authoritative server was queried. So the *effective* TTL is the TTL the client sees + however long this record has been in `encrypted-dns-server`'s cache. Which in this case is usually more than the TTL the zone owner had set.

If a long enough chain of caching resolvers can keep telling the next one down that a record is fresh for the next TTL seconds when the last time the authoritative name sever was queried was potentially several TTLs ago, how could any zone administrator trust that their records have propagated?

Granted, the RFCs aren't clear on this and could be interpreted either way, but I really feel like the *effective* TTL shouldn't depend on how many caches there are between the client and the authoritative server.

> traffic

I can understand that caches expiring all at once would create a spike in queries but then why do other caching resolvers tick down TTL?

> Not decreasing TTLs in intermediate caches is equivalent to having a local resolver without intermediates.

I don't understand this part.
